# Generated by Django 3.2 on 2021-06-20 21:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store', models.CharField(choices=[('costco', 'Costco'), ('kph', 'KIM PHAT')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('receipts', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
