# Generated by Django 3.2 on 2021-06-23 19:55

from django.db import migrations, models
import django.db.models.deletion
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20210621_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipts',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=receipts.models.get_image_filename, verbose_name='Image')),
                ('receipt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt')),
            ],
        ),
    ]
