# Generated by Django 3.2 on 2021-07-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20210623_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt'),
        ),
    ]
