# Generated by Django 3.2 on 2021-04-23 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 22, 6, 17, 90589, tzinfo=utc)),
        ),
    ]
