# Generated by Django 3.2 on 2021-04-25 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210425_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 50, 29, 95800, tzinfo=utc)),
        ),
    ]
