# Generated by Django 3.2 on 2021-06-17 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20210428_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 18, 57, 23, 304025, tzinfo=utc)),
        ),
    ]
