# Generated by Django 3.2 on 2021-06-23 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 19, 55, 52, 80484, tzinfo=utc)),
        ),
    ]
