# Generated by Django 3.2 on 2021-06-25 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 0, 39, 49, 516539, tzinfo=utc)),
        ),
    ]
