# Generated by Django 3.2 on 2021-07-19 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 1, 48, 1, 456139, tzinfo=utc)),
        ),
    ]
