# Generated by Django 3.2 on 2021-07-29 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 4, 57, 5, 757212, tzinfo=utc)),
        ),
    ]
