# Generated by Django 2.2.20 on 2021-04-09 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 17, 35, 5, 518876)),
        ),
        migrations.AddField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 21, 35, 5, 518808, tzinfo=utc), verbose_name='data filled'),
        ),
    ]
