# Generated by Django 3.2 on 2021-04-18 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0003_auto_20210417_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 2, 24, 53, 100416, tzinfo=utc), verbose_name='data filled'),
        ),
    ]
