# Generated by Django 3.2 on 2021-04-18 02:46

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0004_alter_bill_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 2, 46, 24, 882767, tzinfo=utc), verbose_name='data filled'),
        ),
    ]
