# Generated by Django 3.2 on 2021-06-17 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0006_auto_20210617_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bill_date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 19, 16, 27, 273214, tzinfo=utc), verbose_name='data filled'),
        ),
    ]
