# Generated by Django 3.2 on 2021-06-19 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0007_auto_20210617_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='location',
        ),
        migrations.AlterField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 5, 7, 992238, tzinfo=utc), verbose_name='data filled'),
        ),
    ]
