# Generated by Django 3.2 on 2021-06-20 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0008_auto_20210619_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 21, 17, 50, 682639, tzinfo=utc), verbose_name='data filled'),
        ),
    ]
