# Generated by Django 3.2 on 2021-06-29 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('util_calculator', '0013_alter_bill_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 21, 14, 53, 576329, tzinfo=utc), verbose_name='data filled'),
        ),
        migrations.AddField(
            model_name='bill',
            name='utility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='util_calculator.utility'),
        ),
        migrations.AddField(
            model_name='payment',
            name='utility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='util_calculator.utility'),
        ),
    ]
